// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atywywskcgixdeliqivw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0eXd5d3NrY2dpeGRlbGlxaXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyODc2OTcsImV4cCI6MjA3Nzg2MzY5N30.SJ589bAl_C5U3wvYAu48HJ6IebnYx-fj6VnJbLOdPlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});